allowBuilds:
  '@prisma/engines': true
  prisma: true
  esbuild: true
  sharp: true
  embedded-postgres: true
  '@embedded-postgres/windows-x64': true
  '@embedded-postgres/linux-x64': true
  unrs-resolver: true
