export type AssetView = {
  change30dPercent?: number | null;
  image: { updatedAt: string } | null;
  id: string;
  name: string;
  symbol: string;
  categoryId: string;
  category: { key: string; label: string; color: string };
  currency: string;
  platform: string;
  subcategory: string | null;
  externalId: string | null;
  notes: string;
  status: string;
  metadata: Record<string, string>;
  version: number;
  deletedAt: string | null;
  quantity: string;
  costEur: string | null;
  costUsd: string | null;
  averagePrice: string | null;
  price: string | null;
  priceDate: string | null;
  stale: boolean;
  valueEur: string | null;
  valueUsd: string | null;
  gainEur: string | null;
  gainUsd: string | null;
  realizedEur: string | null;
  places: Record<string, string>;
};
export type TransactionView = {
  id: string;
  assetId: string | null;
  assetName: string;
  type: string;
  quantity: string;
  unitPrice: string;
  amount: string;
  fees: string;
  currency: 'EUR' | 'USD';
  platform: string;
  destination: string | null;
  settlement: 'INTERNAL' | 'EXTERNAL';
  occurredAt: string;
  comment: string;
  externalReference: string | null;
  version: number;
};
export type SnapshotView = {
  categoryValues?: Record<string, { valueEur: string | null; valueUsd: string | null }>;
  id: string;
  capturedAt: string;
  kind: string;
  totalEur: string | null;
  totalUsd: string | null;
  investedEur: string | null;
  ledgerVersion: number;
};
export type CategoryHistoryPoint = { date: string; value: number | null };
export type AssetCategorySummary = {
  id: string;
  slug: string;
  name: string;
  color: string;
  totalValue: number | null;
  assetCount: number;
  portfolioWeight: number | null;
  change30dPercent: number | null;
  change30dAbsolute: number | null;
  baselineDate: string | null;
};
export type CategoryPosition = {
  id: string;
  name: string;
  href: string;
  quantity: string | null;
  price: string | null;
  priceCurrency: string;
  value: number | null;
  cost: number | null;
  change30dPercent: number | null;
  isAdjustment?: boolean;
};
export type AssetCategoryDetails = {
  category: AssetCategorySummary;
  investedCapital: number | null;
  unrealizedPnL: number | null;
  unrealizedPnLPercent: number | null;
  history: CategoryHistoryPoint[];
  assets: CategoryPosition[];
};
export type AppState = {
  onchain: import('./wallets').OnchainState;
  asOf: string;
  historyRevised: boolean;
  portfolio: {
    id: string;
    name: string;
    displayCurrency: 'EUR' | 'USD';
    timezone: 'Europe/Paris' | 'UTC';
    isDemo: boolean;
    version: number;
  };
  rows: AssetView[];
  transactions: TransactionView[];
  categories: { id: string; key: string; label: string; color: string }[];
  snapshots: SnapshotView[];
  cash: {
    currency: string;
    platform: string;
    balance: string;
    valueEur: string | null;
    valueUsd: string | null;
  }[];
  totals: {
    valueEur: string | null;
    valueUsd: string | null;
    subtotalEur: string;
    costEur: string | null;
    costUsd: string | null;
    realizedEur: string | null;
    incompleteCostBasis: boolean;
    unrealizedEur: string | null;
    netFlowsEur: string;
    purchasesEur: string;
    incomeEur: string;
    expensesEur: string;
    missingEur: number;
    missingUsd: number;
  };
  fxRate: { eurUsd: string; observedAt: string; source: string } | null;
  flows: { amount: string; date: string }[];
};
