import { chromium } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
const credentials = JSON.parse(readFileSync('.local/demo-access.json', 'utf8'));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1060 } });
const errors: string[] = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (['error','warning'].includes(message.type())) errors.push(message.text()); });
await page.goto('http://localhost:3000/login');
await page.getByLabel('Adresse e-mail').fill(credentials.email);
await page.getByLabel('Mot de passe', { exact: true }).fill(credentials.password);
await page.getByRole('button', { name: 'Ouvrir mon portefeuille' }).click();
await page.waitForURL('**/dashboard');
await page.getByText('Valeur du patrimoine', { exact: true }).waitFor();
await page.locator('.recharts-surface').first().waitFor();
mkdirSync('.local/screenshots', { recursive: true });
await page.screenshot({ path: '.local/screenshots/dashboard.png', fullPage: true });
await page.setViewportSize({ width: 375, height: 812 });
await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth + 1);
await page.screenshot({ path: '.local/screenshots/mobile.png', fullPage: true });
console.log(JSON.stringify({ page: await page.title(), browserErrors: errors }));
await browser.close();
